<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">

<!-- Begin Jekyll SEO tag v2.7.1 -->
<title>100-Days-Python | Udemy 100 days of Python</title>
<meta name="generator" content="Jekyll v3.9.0" />
<meta property="og:title" content="100-Days-Python" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Udemy 100 days of Python" />
<meta property="og:description" content="Udemy 100 days of Python" />
<link rel="canonical" href="https://yawnee.github.io/100-Days-Python/" />
<meta property="og:url" content="https://yawnee.github.io/100-Days-Python/" />
<meta property="og:site_name" content="100-Days-Python" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="100-Days-Python" />
<script type="application/ld+json">
{"description":"Udemy 100 days of Python","url":"https://yawnee.github.io/100-Days-Python/","@type":"WebSite","headline":"100-Days-Python","name":"100-Days-Python","@context":"https://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" as="style" type="text/css" crossorigin>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#157878">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="stylesheet" href="/100-Days-Python/assets/css/style.css?v=53ec8aa201a4bc3c05eefb6811c768738155c662">
    <!-- start custom head snippets, customize with your own _includes/head-custom.html file -->

<!-- Setup Google Analytics -->



<!-- You can set your favicon here -->
<!-- link rel="shortcut icon" type="image/x-icon" href="/100-Days-Python/favicon.ico" -->

<!-- end custom head snippets -->

  </head>
  <body>
    <a id="skip-to-content" href="#content">Skip to the content.</a>

    <header class="page-header" role="banner">
      <h1 class="project-name">100-Days-Python</h1>
      <h2 class="project-tagline">Udemy 100 days of Python</h2>
      
        <a href="https://github.com/yawnee/100-Days-Python" class="btn">View on GitHub</a>
      
      
    </header>

    <main id="content" class="main-content" role="main">
      <p>My journey on completing the Udemy course “100 Days of Python”.
Reference: 100 Days of Code: The Complete Python Pro Bootcamp for 2022.</p>


      <footer class="site-footer">
        
          <span class="site-footer-owner"><a href="https://github.com/yawnee/100-Days-Python">100-Days-Python</a> is maintained by <a href="https://github.com/yawnee">yawnee</a>.</span>
        
        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
      </footer>
    </main>
  </body>
</html>
